POST http://localhost:8000/api/produtos/
Content-Type: application/json

{
    "nome": "Notebook 3",
    "descricao": "Notebook Dell 3",
    "preco": 3500.00,
    "estoque": 10,
    "ativo": true
}

### 
GET http://localhost:8000/api/produtos/